### ISSUE TITLE
Potential dataset to convert: Ferguson et al CA1 pyramidal cell

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/NWBShowcase#2]
https://www.zenodo.org/record/17794#.W5j7lBQnYYM

Will need this:
https://pypi.org/project/pyabf/

In progress here: https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/TestData.ipynb

**Comment by filippometacell** [comment]
Made a little change since the 'keyword' argument is breaking the file load. Also filed an issue on pynwb https://github.com/NeurodataWithoutBorders/pynwb/issues/837

**Comment by pgleeson** [comment]
Converted and added to NWBE homepage
